var annotated_dup =
[
    [ "kuzu", "namespacekuzu.html", [
      [ "binder", "namespacekuzu_1_1binder.html", [
        [ "Expression", "classkuzu_1_1binder_1_1_expression.html", "classkuzu_1_1binder_1_1_expression" ],
        [ "ExpressionEquality", "structkuzu_1_1binder_1_1_expression_equality.html", "structkuzu_1_1binder_1_1_expression_equality" ],
        [ "ExpressionHasher", "structkuzu_1_1binder_1_1_expression_hasher.html", "structkuzu_1_1binder_1_1_expression_hasher" ]
      ] ],
      [ "common", "namespacekuzu_1_1common.html", [
        [ "ArrayType", "structkuzu_1_1common_1_1_array_type.html", null ],
        [ "ArrayTypeInfo", "classkuzu_1_1common_1_1_array_type_info.html", "classkuzu_1_1common_1_1_array_type_info" ],
        [ "ArrowColumnAuxiliaryBuffer", "classkuzu_1_1common_1_1_arrow_column_auxiliary_buffer.html", "classkuzu_1_1common_1_1_arrow_column_auxiliary_buffer" ],
        [ "AuxiliaryBuffer", "classkuzu_1_1common_1_1_auxiliary_buffer.html", "classkuzu_1_1common_1_1_auxiliary_buffer" ],
        [ "AuxiliaryBufferFactory", "classkuzu_1_1common_1_1_auxiliary_buffer_factory.html", null ],
        [ "BinderException", "classkuzu_1_1common_1_1_binder_exception.html", "classkuzu_1_1common_1_1_binder_exception" ],
        [ "Blob", "structkuzu_1_1common_1_1_blob.html", null ],
        [ "blob_t", "structkuzu_1_1common_1_1blob__t.html", "structkuzu_1_1common_1_1blob__t" ],
        [ "BlobVector", "structkuzu_1_1common_1_1_blob_vector.html", null ],
        [ "BufferBlock", "structkuzu_1_1common_1_1_buffer_block.html", "structkuzu_1_1common_1_1_buffer_block" ],
        [ "BufferPoolConstants", "structkuzu_1_1common_1_1_buffer_pool_constants.html", null ],
        [ "CaseInsensitiveStringEquality", "structkuzu_1_1common_1_1_case_insensitive_string_equality.html", "structkuzu_1_1common_1_1_case_insensitive_string_equality" ],
        [ "CaseInsensitiveStringHashFunction", "structkuzu_1_1common_1_1_case_insensitive_string_hash_function.html", "structkuzu_1_1common_1_1_case_insensitive_string_hash_function" ],
        [ "CatalogException", "classkuzu_1_1common_1_1_catalog_exception.html", "classkuzu_1_1common_1_1_catalog_exception" ],
        [ "CopyConstants", "structkuzu_1_1common_1_1_copy_constants.html", null ],
        [ "CSVOption", "structkuzu_1_1common_1_1_c_s_v_option.html", "structkuzu_1_1common_1_1_c_s_v_option" ],
        [ "CSVReaderConfig", "structkuzu_1_1common_1_1_c_s_v_reader_config.html", "structkuzu_1_1common_1_1_c_s_v_reader_config" ],
        [ "DataChunk", "classkuzu_1_1common_1_1_data_chunk.html", "classkuzu_1_1common_1_1_data_chunk" ],
        [ "DataChunkState", "classkuzu_1_1common_1_1_data_chunk_state.html", "classkuzu_1_1common_1_1_data_chunk_state" ],
        [ "Date", "classkuzu_1_1common_1_1_date.html", null ],
        [ "date_t", "structkuzu_1_1common_1_1date__t.html", "structkuzu_1_1common_1_1date__t" ],
        [ "DecimalType", "structkuzu_1_1common_1_1_decimal_type.html", null ],
        [ "DecimalTypeInfo", "classkuzu_1_1common_1_1_decimal_type_info.html", "classkuzu_1_1common_1_1_decimal_type_info" ],
        [ "dtime_t", "structkuzu_1_1common_1_1dtime__t.html", "structkuzu_1_1common_1_1dtime__t" ],
        [ "Exception", "classkuzu_1_1common_1_1_exception.html", "classkuzu_1_1common_1_1_exception" ],
        [ "ExportCSVConstants", "structkuzu_1_1common_1_1_export_c_s_v_constants.html", null ],
        [ "ExpressionTypeUtil", "structkuzu_1_1common_1_1_expression_type_util.html", null ],
        [ "ExtraTypeInfo", "classkuzu_1_1common_1_1_extra_type_info.html", "classkuzu_1_1common_1_1_extra_type_info" ],
        [ "FileScanInfo", "structkuzu_1_1common_1_1_file_scan_info.html", "structkuzu_1_1common_1_1_file_scan_info" ],
        [ "FileTypeInfo", "structkuzu_1_1common_1_1_file_type_info.html", "structkuzu_1_1common_1_1_file_type_info" ],
        [ "FileTypeUtils", "structkuzu_1_1common_1_1_file_type_utils.html", null ],
        [ "HashIndexConstants", "structkuzu_1_1common_1_1_hash_index_constants.html", null ],
        [ "HexFormatConstants", "structkuzu_1_1common_1_1_hex_format_constants.html", null ],
        [ "InMemOverflowBuffer", "classkuzu_1_1common_1_1_in_mem_overflow_buffer.html", "classkuzu_1_1common_1_1_in_mem_overflow_buffer" ],
        [ "Int128_t", "classkuzu_1_1common_1_1_int128__t.html", "classkuzu_1_1common_1_1_int128__t" ],
        [ "int128_t", "structkuzu_1_1common_1_1int128__t.html", "structkuzu_1_1common_1_1int128__t" ],
        [ "InternalException", "classkuzu_1_1common_1_1_internal_exception.html", "classkuzu_1_1common_1_1_internal_exception" ],
        [ "internalID_t", "structkuzu_1_1common_1_1internal_i_d__t.html", "structkuzu_1_1common_1_1internal_i_d__t" ],
        [ "InternalKeyword", "structkuzu_1_1common_1_1_internal_keyword.html", null ],
        [ "Interval", "classkuzu_1_1common_1_1_interval.html", null ],
        [ "interval_t", "structkuzu_1_1common_1_1interval__t.html", "structkuzu_1_1common_1_1interval__t" ],
        [ "ku_list_t", "structkuzu_1_1common_1_1ku__list__t.html", "structkuzu_1_1common_1_1ku__list__t" ],
        [ "ku_string_t", "structkuzu_1_1common_1_1ku__string__t.html", "structkuzu_1_1common_1_1ku__string__t" ],
        [ "ku_uuid_t", "structkuzu_1_1common_1_1ku__uuid__t.html", "structkuzu_1_1common_1_1ku__uuid__t" ],
        [ "list_entry_t", "structkuzu_1_1common_1_1list__entry__t.html", "structkuzu_1_1common_1_1list__entry__t" ],
        [ "ListAuxiliaryBuffer", "classkuzu_1_1common_1_1_list_auxiliary_buffer.html", "classkuzu_1_1common_1_1_list_auxiliary_buffer" ],
        [ "ListType", "structkuzu_1_1common_1_1_list_type.html", null ],
        [ "ListTypeInfo", "classkuzu_1_1common_1_1_list_type_info.html", "classkuzu_1_1common_1_1_list_type_info" ],
        [ "ListVector", "classkuzu_1_1common_1_1_list_vector.html", null ],
        [ "LogicalType", "classkuzu_1_1common_1_1_logical_type.html", "classkuzu_1_1common_1_1_logical_type" ],
        [ "LogicalTypeUtils", "structkuzu_1_1common_1_1_logical_type_utils.html", null ],
        [ "map_entry_t", "structkuzu_1_1common_1_1map__entry__t.html", "structkuzu_1_1common_1_1map__entry__t" ],
        [ "MapType", "structkuzu_1_1common_1_1_map_type.html", null ],
        [ "MapVector", "classkuzu_1_1common_1_1_map_vector.html", null ],
        [ "NestedVal", "classkuzu_1_1common_1_1_nested_val.html", null ],
        [ "NodeVal", "classkuzu_1_1common_1_1_node_val.html", null ],
        [ "NullMask", "classkuzu_1_1common_1_1_null_mask.html", "classkuzu_1_1common_1_1_null_mask" ],
        [ "OrderByConstants", "structkuzu_1_1common_1_1_order_by_constants.html", null ],
        [ "overflow_value_t", "structkuzu_1_1common_1_1overflow__value__t.html", "structkuzu_1_1common_1_1overflow__value__t" ],
        [ "overload", "structkuzu_1_1common_1_1overload.html", "structkuzu_1_1common_1_1overload" ],
        [ "ParquetConstants", "structkuzu_1_1common_1_1_parquet_constants.html", null ],
        [ "PathSemanticUtils", "structkuzu_1_1common_1_1_path_semantic_utils.html", null ],
        [ "PhysicalTypeUtils", "structkuzu_1_1common_1_1_physical_type_utils.html", null ],
        [ "PlannerKnobs", "structkuzu_1_1common_1_1_planner_knobs.html", null ],
        [ "PortDBConstants", "structkuzu_1_1common_1_1_port_d_b_constants.html", null ],
        [ "RecursiveRelVal", "classkuzu_1_1common_1_1_recursive_rel_val.html", null ],
        [ "RelVal", "classkuzu_1_1common_1_1_rel_val.html", null ],
        [ "SelectionVector", "classkuzu_1_1common_1_1_selection_vector.html", "classkuzu_1_1common_1_1_selection_vector" ],
        [ "StorageConstants", "structkuzu_1_1common_1_1_storage_constants.html", null ],
        [ "StringAuxiliaryBuffer", "classkuzu_1_1common_1_1_string_auxiliary_buffer.html", "classkuzu_1_1common_1_1_string_auxiliary_buffer" ],
        [ "StringVector", "classkuzu_1_1common_1_1_string_vector.html", null ],
        [ "struct_entry_t", "structkuzu_1_1common_1_1struct__entry__t.html", "structkuzu_1_1common_1_1struct__entry__t" ],
        [ "StructAuxiliaryBuffer", "classkuzu_1_1common_1_1_struct_auxiliary_buffer.html", "classkuzu_1_1common_1_1_struct_auxiliary_buffer" ],
        [ "StructField", "classkuzu_1_1common_1_1_struct_field.html", "classkuzu_1_1common_1_1_struct_field" ],
        [ "StructType", "structkuzu_1_1common_1_1_struct_type.html", null ],
        [ "StructTypeInfo", "classkuzu_1_1common_1_1_struct_type_info.html", "classkuzu_1_1common_1_1_struct_type_info" ],
        [ "StructVector", "classkuzu_1_1common_1_1_struct_vector.html", null ],
        [ "TableOptionConstants", "structkuzu_1_1common_1_1_table_option_constants.html", null ],
        [ "Time", "classkuzu_1_1common_1_1_time.html", null ],
        [ "Timer", "classkuzu_1_1common_1_1_timer.html", "classkuzu_1_1common_1_1_timer" ],
        [ "Timestamp", "classkuzu_1_1common_1_1_timestamp.html", null ],
        [ "timestamp_ms_t", "structkuzu_1_1common_1_1timestamp__ms__t.html", "structkuzu_1_1common_1_1timestamp__ms__t" ],
        [ "timestamp_ns_t", "structkuzu_1_1common_1_1timestamp__ns__t.html", "structkuzu_1_1common_1_1timestamp__ns__t" ],
        [ "timestamp_sec_t", "structkuzu_1_1common_1_1timestamp__sec__t.html", "structkuzu_1_1common_1_1timestamp__sec__t" ],
        [ "timestamp_t", "structkuzu_1_1common_1_1timestamp__t.html", "structkuzu_1_1common_1_1timestamp__t" ],
        [ "timestamp_tz_t", "structkuzu_1_1common_1_1timestamp__tz__t.html", "structkuzu_1_1common_1_1timestamp__tz__t" ],
        [ "TypeUtils", "classkuzu_1_1common_1_1_type_utils.html", "classkuzu_1_1common_1_1_type_utils" ],
        [ "UDTTypeInfo", "classkuzu_1_1common_1_1_u_d_t_type_info.html", "classkuzu_1_1common_1_1_u_d_t_type_info" ],
        [ "union_entry_t", "structkuzu_1_1common_1_1union__entry__t.html", "structkuzu_1_1common_1_1union__entry__t" ],
        [ "UnionType", "structkuzu_1_1common_1_1_union_type.html", null ],
        [ "UnionVector", "classkuzu_1_1common_1_1_union_vector.html", null ],
        [ "UUID", "structkuzu_1_1common_1_1_u_u_i_d.html", null ],
        [ "Value", "classkuzu_1_1common_1_1_value.html", "classkuzu_1_1common_1_1_value" ],
        [ "ValueVector", "classkuzu_1_1common_1_1_value_vector.html", "classkuzu_1_1common_1_1_value_vector" ],
        [ "WarningConstants", "structkuzu_1_1common_1_1_warning_constants.html", null ]
      ] ],
      [ "function", "namespacekuzu_1_1function.html", [
        [ "BinaryComparisonFunctionWrapper", "structkuzu_1_1function_1_1_binary_comparison_function_wrapper.html", null ],
        [ "BinaryFunctionExecutor", "structkuzu_1_1function_1_1_binary_function_executor.html", "structkuzu_1_1function_1_1_binary_function_executor" ],
        [ "BinaryFunctionWrapper", "structkuzu_1_1function_1_1_binary_function_wrapper.html", null ],
        [ "BinaryListExtractFunctionWrapper", "structkuzu_1_1function_1_1_binary_list_extract_function_wrapper.html", null ],
        [ "BinaryListStructFunctionWrapper", "structkuzu_1_1function_1_1_binary_list_struct_function_wrapper.html", null ],
        [ "BinaryMapCreationFunctionWrapper", "structkuzu_1_1function_1_1_binary_map_creation_function_wrapper.html", null ],
        [ "BinaryStringFunctionWrapper", "structkuzu_1_1function_1_1_binary_string_function_wrapper.html", null ],
        [ "BinaryUDFExecutor", "structkuzu_1_1function_1_1_binary_u_d_f_executor.html", null ],
        [ "BinaryUDFFunctionWrapper", "structkuzu_1_1function_1_1_binary_u_d_f_function_wrapper.html", null ],
        [ "CastFunctionBindData", "structkuzu_1_1function_1_1_cast_function_bind_data.html", "structkuzu_1_1function_1_1_cast_function_bind_data" ],
        [ "ConstFunctionExecutor", "structkuzu_1_1function_1_1_const_function_executor.html", null ],
        [ "ExtraScanTableFuncBindInput", "structkuzu_1_1function_1_1_extra_scan_table_func_bind_input.html", "structkuzu_1_1function_1_1_extra_scan_table_func_bind_input" ],
        [ "ExtraTableFuncBindInput", "structkuzu_1_1function_1_1_extra_table_func_bind_input.html", "structkuzu_1_1function_1_1_extra_table_func_bind_input" ],
        [ "Function", "structkuzu_1_1function_1_1_function.html", "structkuzu_1_1function_1_1_function" ],
        [ "FunctionBindData", "structkuzu_1_1function_1_1_function_bind_data.html", "structkuzu_1_1function_1_1_function_bind_data" ],
        [ "PointerFunctionExecutor", "structkuzu_1_1function_1_1_pointer_function_executor.html", null ],
        [ "ScalarBindFuncInput", "structkuzu_1_1function_1_1_scalar_bind_func_input.html", "structkuzu_1_1function_1_1_scalar_bind_func_input" ],
        [ "ScalarFunction", "structkuzu_1_1function_1_1_scalar_function.html", "structkuzu_1_1function_1_1_scalar_function" ],
        [ "ScalarOrAggregateFunction", "structkuzu_1_1function_1_1_scalar_or_aggregate_function.html", "structkuzu_1_1function_1_1_scalar_or_aggregate_function" ],
        [ "ScanReplacement", "structkuzu_1_1function_1_1_scan_replacement.html", "structkuzu_1_1function_1_1_scan_replacement" ],
        [ "ScanReplacementData", "structkuzu_1_1function_1_1_scan_replacement_data.html", "structkuzu_1_1function_1_1_scan_replacement_data" ],
        [ "TableFuncBindInput", "structkuzu_1_1function_1_1_table_func_bind_input.html", "structkuzu_1_1function_1_1_table_func_bind_input" ],
        [ "TableFuncInput", "structkuzu_1_1function_1_1_table_func_input.html", "structkuzu_1_1function_1_1_table_func_input" ],
        [ "TableFuncLocalState", "structkuzu_1_1function_1_1_table_func_local_state.html", "structkuzu_1_1function_1_1_table_func_local_state" ],
        [ "TableFuncOutput", "structkuzu_1_1function_1_1_table_func_output.html", "structkuzu_1_1function_1_1_table_func_output" ],
        [ "TableFuncSharedState", "structkuzu_1_1function_1_1_table_func_shared_state.html", "structkuzu_1_1function_1_1_table_func_shared_state" ],
        [ "TableFunction", "structkuzu_1_1function_1_1_table_function.html", "structkuzu_1_1function_1_1_table_function" ],
        [ "TableFunctionInitInput", "structkuzu_1_1function_1_1_table_function_init_input.html", "structkuzu_1_1function_1_1_table_function_init_input" ],
        [ "TernaryFunctionExecutor", "structkuzu_1_1function_1_1_ternary_function_executor.html", null ],
        [ "TernaryFunctionWrapper", "structkuzu_1_1function_1_1_ternary_function_wrapper.html", null ],
        [ "TernaryListFunctionWrapper", "structkuzu_1_1function_1_1_ternary_list_function_wrapper.html", null ],
        [ "TernaryRegexFunctionWrapper", "structkuzu_1_1function_1_1_ternary_regex_function_wrapper.html", null ],
        [ "TernaryStringFunctionWrapper", "structkuzu_1_1function_1_1_ternary_string_function_wrapper.html", null ],
        [ "TernaryUDFExecutor", "structkuzu_1_1function_1_1_ternary_u_d_f_executor.html", null ],
        [ "TernaryUDFFunctionWrapper", "structkuzu_1_1function_1_1_ternary_u_d_f_function_wrapper.html", null ],
        [ "UDF", "structkuzu_1_1function_1_1_u_d_f.html", null ],
        [ "UnaryCastFunctionWrapper", "structkuzu_1_1function_1_1_unary_cast_function_wrapper.html", null ],
        [ "UnaryCastStringFunctionWrapper", "structkuzu_1_1function_1_1_unary_cast_string_function_wrapper.html", null ],
        [ "UnaryFunctionExecutor", "structkuzu_1_1function_1_1_unary_function_executor.html", null ],
        [ "UnaryFunctionWrapper", "structkuzu_1_1function_1_1_unary_function_wrapper.html", null ],
        [ "UnaryNestedTypeFunctionWrapper", "structkuzu_1_1function_1_1_unary_nested_type_function_wrapper.html", null ],
        [ "UnarySequenceFunctionWrapper", "structkuzu_1_1function_1_1_unary_sequence_function_wrapper.html", null ],
        [ "UnaryStringFunctionWrapper", "structkuzu_1_1function_1_1_unary_string_function_wrapper.html", null ],
        [ "UnaryStructFunctionWrapper", "structkuzu_1_1function_1_1_unary_struct_function_wrapper.html", null ],
        [ "UnaryUDFExecutor", "structkuzu_1_1function_1_1_unary_u_d_f_executor.html", null ],
        [ "UnaryUDFFunctionWrapper", "structkuzu_1_1function_1_1_unary_u_d_f_function_wrapper.html", null ]
      ] ],
      [ "main", "namespacekuzu_1_1main.html", [
        [ "ActiveQuery", "structkuzu_1_1main_1_1_active_query.html", "structkuzu_1_1main_1_1_active_query" ],
        [ "ClientConfig", "structkuzu_1_1main_1_1_client_config.html", "structkuzu_1_1main_1_1_client_config" ],
        [ "ClientConfigDefault", "structkuzu_1_1main_1_1_client_config_default.html", null ],
        [ "ClientContext", "classkuzu_1_1main_1_1_client_context.html", "classkuzu_1_1main_1_1_client_context" ],
        [ "ConfigurationOption", "structkuzu_1_1main_1_1_configuration_option.html", "structkuzu_1_1main_1_1_configuration_option" ],
        [ "Connection", "classkuzu_1_1main_1_1_connection.html", "classkuzu_1_1main_1_1_connection" ],
        [ "Database", "classkuzu_1_1main_1_1_database.html", "classkuzu_1_1main_1_1_database" ],
        [ "DBConfig", "structkuzu_1_1main_1_1_d_b_config.html", "structkuzu_1_1main_1_1_d_b_config" ],
        [ "ExtensionOption", "structkuzu_1_1main_1_1_extension_option.html", "structkuzu_1_1main_1_1_extension_option" ],
        [ "Option", "structkuzu_1_1main_1_1_option.html", "structkuzu_1_1main_1_1_option" ],
        [ "PreparedStatement", "classkuzu_1_1main_1_1_prepared_statement.html", "classkuzu_1_1main_1_1_prepared_statement" ],
        [ "PreparedSummary", "structkuzu_1_1main_1_1_prepared_summary.html", "structkuzu_1_1main_1_1_prepared_summary" ],
        [ "QueryResult", "classkuzu_1_1main_1_1_query_result.html", "classkuzu_1_1main_1_1_query_result" ],
        [ "QuerySummary", "classkuzu_1_1main_1_1_query_summary.html", "classkuzu_1_1main_1_1_query_summary" ],
        [ "StorageDriver", "classkuzu_1_1main_1_1_storage_driver.html", "classkuzu_1_1main_1_1_storage_driver" ],
        [ "SystemConfig", "structkuzu_1_1main_1_1_system_config.html", "structkuzu_1_1main_1_1_system_config" ],
        [ "Version", "structkuzu_1_1main_1_1_version.html", null ]
      ] ],
      [ "parser", "namespacekuzu_1_1parser.html", [
        [ "Statement", "classkuzu_1_1parser_1_1_statement.html", "classkuzu_1_1parser_1_1_statement" ],
        [ "YieldVariable", "structkuzu_1_1parser_1_1_yield_variable.html", "structkuzu_1_1parser_1_1_yield_variable" ]
      ] ],
      [ "processor", "namespacekuzu_1_1processor.html", [
        [ "CopyFromFileError", "structkuzu_1_1processor_1_1_copy_from_file_error.html", "structkuzu_1_1processor_1_1_copy_from_file_error" ],
        [ "FlatTuple", "classkuzu_1_1processor_1_1_flat_tuple.html", "classkuzu_1_1processor_1_1_flat_tuple" ],
        [ "LineContext", "structkuzu_1_1processor_1_1_line_context.html", "structkuzu_1_1processor_1_1_line_context" ],
        [ "PopulatedCopyFromError", "structkuzu_1_1processor_1_1_populated_copy_from_error.html", "structkuzu_1_1processor_1_1_populated_copy_from_error" ],
        [ "WarningContext", "classkuzu_1_1processor_1_1_warning_context.html", "classkuzu_1_1processor_1_1_warning_context" ],
        [ "WarningInfo", "structkuzu_1_1processor_1_1_warning_info.html", "structkuzu_1_1processor_1_1_warning_info" ],
        [ "WarningSourceData", "structkuzu_1_1processor_1_1_warning_source_data.html", "structkuzu_1_1processor_1_1_warning_source_data" ]
      ] ],
      [ "storage", "namespacekuzu_1_1storage.html", [
        [ "StorageVersionInfo", "structkuzu_1_1storage_1_1_storage_version_info.html", null ]
      ] ],
      [ "transaction", "namespacekuzu_1_1transaction.html", [
        [ "Transaction", "classkuzu_1_1transaction_1_1_transaction.html", "classkuzu_1_1transaction_1_1_transaction" ],
        [ "TransactionContext", "classkuzu_1_1transaction_1_1_transaction_context.html", "classkuzu_1_1transaction_1_1_transaction_context" ]
      ] ]
    ] ],
    [ "std", null, [
      [ "hash< kuzu::common::int128_t >", "structstd_1_1hash_3_01kuzu_1_1common_1_1int128__t_01_4.html", "structstd_1_1hash_3_01kuzu_1_1common_1_1int128__t_01_4" ]
    ] ],
    [ "ArrowArray", "struct_arrow_array.html", "struct_arrow_array" ],
    [ "ArrowArrayWrapper", "struct_arrow_array_wrapper.html", "struct_arrow_array_wrapper" ],
    [ "ArrowSchema", "struct_arrow_schema.html", "struct_arrow_schema" ],
    [ "ArrowSchemaWrapper", "struct_arrow_schema_wrapper.html", "struct_arrow_schema_wrapper" ]
];