var annotated_dup =
[
    [ "kuzu", "namespacekuzu.html", [
      [ "binder", "namespacekuzu_1_1binder.html", [
        [ "Expression", "classkuzu_1_1binder_1_1_expression.html", "classkuzu_1_1binder_1_1_expression" ],
        [ "ExpressionEquality", "structkuzu_1_1binder_1_1_expression_equality.html", "structkuzu_1_1binder_1_1_expression_equality" ],
        [ "ExpressionHasher", "structkuzu_1_1binder_1_1_expression_hasher.html", "structkuzu_1_1binder_1_1_expression_hasher" ]
      ] ],
      [ "common", "namespacekuzu_1_1common.html", [
        [ "ArrowColumnAuxiliaryBuffer", "classkuzu_1_1common_1_1_arrow_column_auxiliary_buffer.html", "classkuzu_1_1common_1_1_arrow_column_auxiliary_buffer" ],
        [ "AuxiliaryBuffer", "classkuzu_1_1common_1_1_auxiliary_buffer.html", "classkuzu_1_1common_1_1_auxiliary_buffer" ],
        [ "AuxiliaryBufferFactory", "classkuzu_1_1common_1_1_auxiliary_buffer_factory.html", null ],
        [ "BinderException", "classkuzu_1_1common_1_1_binder_exception.html", "classkuzu_1_1common_1_1_binder_exception" ],
        [ "Blob", "structkuzu_1_1common_1_1_blob.html", null ],
        [ "blob_t", "structkuzu_1_1common_1_1blob__t.html", "structkuzu_1_1common_1_1blob__t" ],
        [ "BlobVector", "structkuzu_1_1common_1_1_blob_vector.html", null ],
        [ "BufferBlock", "structkuzu_1_1common_1_1_buffer_block.html", "structkuzu_1_1common_1_1_buffer_block" ],
        [ "BufferPoolConstants", "structkuzu_1_1common_1_1_buffer_pool_constants.html", null ],
        [ "CatalogException", "classkuzu_1_1common_1_1_catalog_exception.html", "classkuzu_1_1common_1_1_catalog_exception" ],
        [ "ClientContextConstants", "structkuzu_1_1common_1_1_client_context_constants.html", null ],
        [ "CopyConstants", "structkuzu_1_1common_1_1_copy_constants.html", null ],
        [ "CopyToCSVConstants", "structkuzu_1_1common_1_1_copy_to_c_s_v_constants.html", null ],
        [ "CSVOption", "structkuzu_1_1common_1_1_c_s_v_option.html", "structkuzu_1_1common_1_1_c_s_v_option" ],
        [ "CSVReaderConfig", "structkuzu_1_1common_1_1_c_s_v_reader_config.html", "structkuzu_1_1common_1_1_c_s_v_reader_config" ],
        [ "DataChunkState", "classkuzu_1_1common_1_1_data_chunk_state.html", "classkuzu_1_1common_1_1_data_chunk_state" ],
        [ "Date", "classkuzu_1_1common_1_1_date.html", null ],
        [ "date_t", "structkuzu_1_1common_1_1date__t.html", "structkuzu_1_1common_1_1date__t" ],
        [ "dtime_t", "structkuzu_1_1common_1_1dtime__t.html", "structkuzu_1_1common_1_1dtime__t" ],
        [ "Exception", "classkuzu_1_1common_1_1_exception.html", "classkuzu_1_1common_1_1_exception" ],
        [ "ExtraTypeInfo", "classkuzu_1_1common_1_1_extra_type_info.html", "classkuzu_1_1common_1_1_extra_type_info" ],
        [ "FileTypeUtils", "structkuzu_1_1common_1_1_file_type_utils.html", null ],
        [ "FixedListType", "structkuzu_1_1common_1_1_fixed_list_type.html", null ],
        [ "FixedListTypeInfo", "classkuzu_1_1common_1_1_fixed_list_type_info.html", "classkuzu_1_1common_1_1_fixed_list_type_info" ],
        [ "FixedListVector", "classkuzu_1_1common_1_1_fixed_list_vector.html", null ],
        [ "HashIndexConstants", "structkuzu_1_1common_1_1_hash_index_constants.html", null ],
        [ "HexFormatConstants", "structkuzu_1_1common_1_1_hex_format_constants.html", null ],
        [ "InMemOverflowBuffer", "classkuzu_1_1common_1_1_in_mem_overflow_buffer.html", "classkuzu_1_1common_1_1_in_mem_overflow_buffer" ],
        [ "Int128_t", "classkuzu_1_1common_1_1_int128__t.html", "classkuzu_1_1common_1_1_int128__t" ],
        [ "int128_t", "structkuzu_1_1common_1_1int128__t.html", "structkuzu_1_1common_1_1int128__t" ],
        [ "InternalException", "classkuzu_1_1common_1_1_internal_exception.html", "classkuzu_1_1common_1_1_internal_exception" ],
        [ "internalID_t", "structkuzu_1_1common_1_1internal_i_d__t.html", "structkuzu_1_1common_1_1internal_i_d__t" ],
        [ "InternalKeyword", "structkuzu_1_1common_1_1_internal_keyword.html", null ],
        [ "Interval", "classkuzu_1_1common_1_1_interval.html", null ],
        [ "interval_t", "structkuzu_1_1common_1_1interval__t.html", "structkuzu_1_1common_1_1interval__t" ],
        [ "ku_list_t", "structkuzu_1_1common_1_1ku__list__t.html", "structkuzu_1_1common_1_1ku__list__t" ],
        [ "ku_string_t", "structkuzu_1_1common_1_1ku__string__t.html", "structkuzu_1_1common_1_1ku__string__t" ],
        [ "list_entry_t", "structkuzu_1_1common_1_1list__entry__t.html", "structkuzu_1_1common_1_1list__entry__t" ],
        [ "ListAuxiliaryBuffer", "classkuzu_1_1common_1_1_list_auxiliary_buffer.html", "classkuzu_1_1common_1_1_list_auxiliary_buffer" ],
        [ "ListVector", "classkuzu_1_1common_1_1_list_vector.html", null ],
        [ "LoggerConstants", "structkuzu_1_1common_1_1_logger_constants.html", "structkuzu_1_1common_1_1_logger_constants" ],
        [ "LogicalType", "classkuzu_1_1common_1_1_logical_type.html", "classkuzu_1_1common_1_1_logical_type" ],
        [ "LogicalTypeUtils", "classkuzu_1_1common_1_1_logical_type_utils.html", null ],
        [ "map_entry_t", "structkuzu_1_1common_1_1map__entry__t.html", "structkuzu_1_1common_1_1map__entry__t" ],
        [ "MapType", "structkuzu_1_1common_1_1_map_type.html", null ],
        [ "MapVector", "classkuzu_1_1common_1_1_map_vector.html", null ],
        [ "NodeType", "structkuzu_1_1common_1_1_node_type.html", null ],
        [ "NullMask", "classkuzu_1_1common_1_1_null_mask.html", "classkuzu_1_1common_1_1_null_mask" ],
        [ "OrderByConstants", "structkuzu_1_1common_1_1_order_by_constants.html", null ],
        [ "overflow_value_t", "structkuzu_1_1common_1_1overflow__value__t.html", "structkuzu_1_1common_1_1overflow__value__t" ],
        [ "ParquetConstants", "structkuzu_1_1common_1_1_parquet_constants.html", null ],
        [ "PhysicalTypeUtils", "structkuzu_1_1common_1_1_physical_type_utils.html", null ],
        [ "PlannerKnobs", "structkuzu_1_1common_1_1_planner_knobs.html", null ],
        [ "RdfReaderConfig", "structkuzu_1_1common_1_1_rdf_reader_config.html", "structkuzu_1_1common_1_1_rdf_reader_config" ],
        [ "ReaderConfig", "structkuzu_1_1common_1_1_reader_config.html", "structkuzu_1_1common_1_1_reader_config" ],
        [ "RelType", "structkuzu_1_1common_1_1_rel_type.html", null ],
        [ "RuntimeException", "classkuzu_1_1common_1_1_runtime_exception.html", "classkuzu_1_1common_1_1_runtime_exception" ],
        [ "SelectionVector", "classkuzu_1_1common_1_1_selection_vector.html", "classkuzu_1_1common_1_1_selection_vector" ],
        [ "StorageConstants", "structkuzu_1_1common_1_1_storage_constants.html", null ],
        [ "StringAuxiliaryBuffer", "classkuzu_1_1common_1_1_string_auxiliary_buffer.html", "classkuzu_1_1common_1_1_string_auxiliary_buffer" ],
        [ "StringVector", "classkuzu_1_1common_1_1_string_vector.html", null ],
        [ "struct_entry_t", "structkuzu_1_1common_1_1struct__entry__t.html", "structkuzu_1_1common_1_1struct__entry__t" ],
        [ "StructAuxiliaryBuffer", "classkuzu_1_1common_1_1_struct_auxiliary_buffer.html", "classkuzu_1_1common_1_1_struct_auxiliary_buffer" ],
        [ "StructField", "classkuzu_1_1common_1_1_struct_field.html", "classkuzu_1_1common_1_1_struct_field" ],
        [ "StructType", "structkuzu_1_1common_1_1_struct_type.html", null ],
        [ "StructTypeInfo", "classkuzu_1_1common_1_1_struct_type_info.html", "classkuzu_1_1common_1_1_struct_type_info" ],
        [ "StructVector", "classkuzu_1_1common_1_1_struct_vector.html", null ],
        [ "Time", "classkuzu_1_1common_1_1_time.html", null ],
        [ "Timer", "classkuzu_1_1common_1_1_timer.html", "classkuzu_1_1common_1_1_timer" ],
        [ "Timestamp", "classkuzu_1_1common_1_1_timestamp.html", null ],
        [ "timestamp_t", "structkuzu_1_1common_1_1timestamp__t.html", "structkuzu_1_1common_1_1timestamp__t" ],
        [ "union_entry_t", "structkuzu_1_1common_1_1union__entry__t.html", "structkuzu_1_1common_1_1union__entry__t" ],
        [ "UnionType", "structkuzu_1_1common_1_1_union_type.html", null ],
        [ "UnionVector", "classkuzu_1_1common_1_1_union_vector.html", null ],
        [ "Value", "classkuzu_1_1common_1_1_value.html", "classkuzu_1_1common_1_1_value" ],
        [ "ValueVector", "classkuzu_1_1common_1_1_value_vector.html", "classkuzu_1_1common_1_1_value_vector" ],
        [ "VarListType", "structkuzu_1_1common_1_1_var_list_type.html", null ],
        [ "VarListTypeInfo", "classkuzu_1_1common_1_1_var_list_type_info.html", "classkuzu_1_1common_1_1_var_list_type_info" ]
      ] ],
      [ "function", "namespacekuzu_1_1function.html", [
        [ "BaseScalarFunction", "structkuzu_1_1function_1_1_base_scalar_function.html", "structkuzu_1_1function_1_1_base_scalar_function" ],
        [ "BinaryComparisonFunctionWrapper", "structkuzu_1_1function_1_1_binary_comparison_function_wrapper.html", null ],
        [ "BinaryFunctionExecutor", "structkuzu_1_1function_1_1_binary_function_executor.html", "structkuzu_1_1function_1_1_binary_function_executor" ],
        [ "BinaryFunctionWrapper", "structkuzu_1_1function_1_1_binary_function_wrapper.html", null ],
        [ "BinaryListExtractFunctionWrapper", "structkuzu_1_1function_1_1_binary_list_extract_function_wrapper.html", null ],
        [ "BinaryListStructFunctionWrapper", "structkuzu_1_1function_1_1_binary_list_struct_function_wrapper.html", null ],
        [ "BinaryStringFunctionWrapper", "structkuzu_1_1function_1_1_binary_string_function_wrapper.html", null ],
        [ "BinaryUDFExecutor", "structkuzu_1_1function_1_1_binary_u_d_f_executor.html", null ],
        [ "BinaryUDFFunctionWrapper", "structkuzu_1_1function_1_1_binary_u_d_f_function_wrapper.html", null ],
        [ "CastChildFunctionExecutor", "structkuzu_1_1function_1_1_cast_child_function_executor.html", null ],
        [ "CastFixedListToListFunctionExecutor", "structkuzu_1_1function_1_1_cast_fixed_list_to_list_function_executor.html", null ],
        [ "CastFunctionBindData", "structkuzu_1_1function_1_1_cast_function_bind_data.html", "structkuzu_1_1function_1_1_cast_function_bind_data" ],
        [ "ConstFunctionExecutor", "structkuzu_1_1function_1_1_const_function_executor.html", null ],
        [ "Function", "structkuzu_1_1function_1_1_function.html", "structkuzu_1_1function_1_1_function" ],
        [ "FunctionBindData", "structkuzu_1_1function_1_1_function_bind_data.html", "structkuzu_1_1function_1_1_function_bind_data" ],
        [ "ScalarFunction", "structkuzu_1_1function_1_1_scalar_function.html", "structkuzu_1_1function_1_1_scalar_function" ],
        [ "TernaryFunctionExecutor", "structkuzu_1_1function_1_1_ternary_function_executor.html", null ],
        [ "TernaryFunctionWrapper", "structkuzu_1_1function_1_1_ternary_function_wrapper.html", null ],
        [ "TernaryListFunctionWrapper", "structkuzu_1_1function_1_1_ternary_list_function_wrapper.html", null ],
        [ "TernaryStringFunctionWrapper", "structkuzu_1_1function_1_1_ternary_string_function_wrapper.html", null ],
        [ "TernaryUDFExecutor", "structkuzu_1_1function_1_1_ternary_u_d_f_executor.html", null ],
        [ "TernaryUDFFunctionWrapper", "structkuzu_1_1function_1_1_ternary_u_d_f_function_wrapper.html", null ],
        [ "UDF", "structkuzu_1_1function_1_1_u_d_f.html", null ],
        [ "UnaryCastFunctionWrapper", "structkuzu_1_1function_1_1_unary_cast_function_wrapper.html", null ],
        [ "UnaryCastStringFunctionWrapper", "structkuzu_1_1function_1_1_unary_cast_string_function_wrapper.html", null ],
        [ "UnaryFunctionExecutor", "structkuzu_1_1function_1_1_unary_function_executor.html", null ],
        [ "UnaryFunctionWrapper", "structkuzu_1_1function_1_1_unary_function_wrapper.html", null ],
        [ "UnaryListFunctionWrapper", "structkuzu_1_1function_1_1_unary_list_function_wrapper.html", null ],
        [ "UnaryStringFunctionWrapper", "structkuzu_1_1function_1_1_unary_string_function_wrapper.html", null ],
        [ "UnaryTryCastFunctionWrapper", "structkuzu_1_1function_1_1_unary_try_cast_function_wrapper.html", null ],
        [ "UnaryUDFExecutor", "structkuzu_1_1function_1_1_unary_u_d_f_executor.html", null ],
        [ "UnaryUDFFunctionWrapper", "structkuzu_1_1function_1_1_unary_u_d_f_function_wrapper.html", null ]
      ] ],
      [ "main", "namespacekuzu_1_1main.html", [
        [ "ActiveQuery", "structkuzu_1_1main_1_1_active_query.html", "structkuzu_1_1main_1_1_active_query" ],
        [ "ClientContext", "classkuzu_1_1main_1_1_client_context.html", "classkuzu_1_1main_1_1_client_context" ],
        [ "Connection", "classkuzu_1_1main_1_1_connection.html", "classkuzu_1_1main_1_1_connection" ],
        [ "Database", "classkuzu_1_1main_1_1_database.html", "classkuzu_1_1main_1_1_database" ],
        [ "DataTypeInfo", "structkuzu_1_1main_1_1_data_type_info.html", "structkuzu_1_1main_1_1_data_type_info" ],
        [ "PreparedStatement", "classkuzu_1_1main_1_1_prepared_statement.html", "classkuzu_1_1main_1_1_prepared_statement" ],
        [ "PreparedSummary", "structkuzu_1_1main_1_1_prepared_summary.html", "structkuzu_1_1main_1_1_prepared_summary" ],
        [ "QueryResult", "classkuzu_1_1main_1_1_query_result.html", "classkuzu_1_1main_1_1_query_result" ],
        [ "QuerySummary", "classkuzu_1_1main_1_1_query_summary.html", "classkuzu_1_1main_1_1_query_summary" ],
        [ "SystemConfig", "structkuzu_1_1main_1_1_system_config.html", "structkuzu_1_1main_1_1_system_config" ]
      ] ],
      [ "processor", "namespacekuzu_1_1processor.html", [
        [ "FlatTuple", "classkuzu_1_1processor_1_1_flat_tuple.html", "classkuzu_1_1processor_1_1_flat_tuple" ]
      ] ],
      [ "storage", "namespacekuzu_1_1storage.html", [
        [ "MemoryAllocator", "classkuzu_1_1storage_1_1_memory_allocator.html", "classkuzu_1_1storage_1_1_memory_allocator" ],
        [ "MemoryBuffer", "classkuzu_1_1storage_1_1_memory_buffer.html", "classkuzu_1_1storage_1_1_memory_buffer" ],
        [ "MemoryManager", "classkuzu_1_1storage_1_1_memory_manager.html", "classkuzu_1_1storage_1_1_memory_manager" ]
      ] ]
    ] ],
    [ "ArrowArray", "struct_arrow_array.html", "struct_arrow_array" ],
    [ "ArrowSchema", "struct_arrow_schema.html", "struct_arrow_schema" ]
];