var hierarchy =
[
    [ "kuzu::main::ActiveQuery", "structkuzu_1_1main_1_1_active_query.html", null ],
    [ "ArrowArray", "struct_arrow_array.html", null ],
    [ "ArrowSchema", "struct_arrow_schema.html", null ],
    [ "kuzu::common::AuxiliaryBuffer", "classkuzu_1_1common_1_1_auxiliary_buffer.html", [
      [ "kuzu::common::ArrowColumnAuxiliaryBuffer", "classkuzu_1_1common_1_1_arrow_column_auxiliary_buffer.html", null ],
      [ "kuzu::common::ListAuxiliaryBuffer", "classkuzu_1_1common_1_1_list_auxiliary_buffer.html", null ],
      [ "kuzu::common::StringAuxiliaryBuffer", "classkuzu_1_1common_1_1_string_auxiliary_buffer.html", null ],
      [ "kuzu::common::StructAuxiliaryBuffer", "classkuzu_1_1common_1_1_struct_auxiliary_buffer.html", null ]
    ] ],
    [ "kuzu::common::AuxiliaryBufferFactory", "classkuzu_1_1common_1_1_auxiliary_buffer_factory.html", null ],
    [ "kuzu::function::BinaryComparisonFunctionWrapper", "structkuzu_1_1function_1_1_binary_comparison_function_wrapper.html", null ],
    [ "kuzu::function::BinaryFunctionExecutor::BinaryComparisonSelectWrapper", "structkuzu_1_1function_1_1_binary_function_executor_1_1_binary_comparison_select_wrapper.html", null ],
    [ "kuzu::function::BinaryFunctionExecutor", "structkuzu_1_1function_1_1_binary_function_executor.html", null ],
    [ "kuzu::function::BinaryFunctionWrapper", "structkuzu_1_1function_1_1_binary_function_wrapper.html", null ],
    [ "kuzu::function::BinaryListExtractFunctionWrapper", "structkuzu_1_1function_1_1_binary_list_extract_function_wrapper.html", null ],
    [ "kuzu::function::BinaryListStructFunctionWrapper", "structkuzu_1_1function_1_1_binary_list_struct_function_wrapper.html", null ],
    [ "kuzu::function::BinaryFunctionExecutor::BinarySelectWrapper", "structkuzu_1_1function_1_1_binary_function_executor_1_1_binary_select_wrapper.html", null ],
    [ "kuzu::function::BinaryStringFunctionWrapper", "structkuzu_1_1function_1_1_binary_string_function_wrapper.html", null ],
    [ "kuzu::function::BinaryUDFExecutor", "structkuzu_1_1function_1_1_binary_u_d_f_executor.html", null ],
    [ "kuzu::function::BinaryUDFFunctionWrapper", "structkuzu_1_1function_1_1_binary_u_d_f_function_wrapper.html", null ],
    [ "kuzu::common::Blob", "structkuzu_1_1common_1_1_blob.html", null ],
    [ "kuzu::common::blob_t", "structkuzu_1_1common_1_1blob__t.html", null ],
    [ "kuzu::common::BlobVector", "structkuzu_1_1common_1_1_blob_vector.html", null ],
    [ "kuzu::common::BufferBlock", "structkuzu_1_1common_1_1_buffer_block.html", null ],
    [ "kuzu::common::BufferPoolConstants", "structkuzu_1_1common_1_1_buffer_pool_constants.html", null ],
    [ "kuzu::function::CastChildFunctionExecutor", "structkuzu_1_1function_1_1_cast_child_function_executor.html", null ],
    [ "kuzu::main::ClientContext", "classkuzu_1_1main_1_1_client_context.html", null ],
    [ "kuzu::common::ClientContextConstants", "structkuzu_1_1common_1_1_client_context_constants.html", null ],
    [ "kuzu::main::Connection", "classkuzu_1_1main_1_1_connection.html", null ],
    [ "kuzu::function::ConstFunctionExecutor", "structkuzu_1_1function_1_1_const_function_executor.html", null ],
    [ "kuzu::common::CopyConstants", "structkuzu_1_1common_1_1_copy_constants.html", null ],
    [ "kuzu::common::CopyToCSVConstants", "structkuzu_1_1common_1_1_copy_to_c_s_v_constants.html", null ],
    [ "kuzu::common::CSVOption", "structkuzu_1_1common_1_1_c_s_v_option.html", [
      [ "kuzu::common::CSVReaderConfig", "structkuzu_1_1common_1_1_c_s_v_reader_config.html", null ]
    ] ],
    [ "kuzu::main::Database", "classkuzu_1_1main_1_1_database.html", null ],
    [ "kuzu::common::DataChunkState", "classkuzu_1_1common_1_1_data_chunk_state.html", null ],
    [ "kuzu::main::DataTypeInfo", "structkuzu_1_1main_1_1_data_type_info.html", null ],
    [ "kuzu::common::Date", "classkuzu_1_1common_1_1_date.html", null ],
    [ "kuzu::common::date_t", "structkuzu_1_1common_1_1date__t.html", null ],
    [ "kuzu::common::dtime_t", "structkuzu_1_1common_1_1dtime__t.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "kuzu::binder::Expression", "classkuzu_1_1binder_1_1_expression.html", null ]
    ] ],
    [ "std::exception", null, [
      [ "kuzu::common::Exception", "classkuzu_1_1common_1_1_exception.html", [
        [ "kuzu::common::BinderException", "classkuzu_1_1common_1_1_binder_exception.html", null ],
        [ "kuzu::common::CatalogException", "classkuzu_1_1common_1_1_catalog_exception.html", null ],
        [ "kuzu::common::InternalException", "classkuzu_1_1common_1_1_internal_exception.html", null ],
        [ "kuzu::common::RuntimeException", "classkuzu_1_1common_1_1_runtime_exception.html", null ]
      ] ]
    ] ],
    [ "kuzu::binder::ExpressionEquality", "structkuzu_1_1binder_1_1_expression_equality.html", null ],
    [ "kuzu::binder::ExpressionHasher", "structkuzu_1_1binder_1_1_expression_hasher.html", null ],
    [ "kuzu::common::ExtraTypeInfo", "classkuzu_1_1common_1_1_extra_type_info.html", [
      [ "kuzu::common::StructTypeInfo", "classkuzu_1_1common_1_1_struct_type_info.html", null ],
      [ "kuzu::common::VarListTypeInfo", "classkuzu_1_1common_1_1_var_list_type_info.html", [
        [ "kuzu::common::FixedListTypeInfo", "classkuzu_1_1common_1_1_fixed_list_type_info.html", null ]
      ] ]
    ] ],
    [ "kuzu::common::FileTypeUtils", "structkuzu_1_1common_1_1_file_type_utils.html", null ],
    [ "kuzu::common::FixedListType", "structkuzu_1_1common_1_1_fixed_list_type.html", null ],
    [ "kuzu::common::FixedListVector", "classkuzu_1_1common_1_1_fixed_list_vector.html", null ],
    [ "kuzu::processor::FlatTuple", "classkuzu_1_1processor_1_1_flat_tuple.html", null ],
    [ "kuzu::function::Function", "structkuzu_1_1function_1_1_function.html", [
      [ "kuzu::function::BaseScalarFunction", "structkuzu_1_1function_1_1_base_scalar_function.html", [
        [ "kuzu::function::ScalarFunction", "structkuzu_1_1function_1_1_scalar_function.html", null ]
      ] ]
    ] ],
    [ "kuzu::function::FunctionBindData", "structkuzu_1_1function_1_1_function_bind_data.html", [
      [ "kuzu::function::CastFunctionBindData", "structkuzu_1_1function_1_1_cast_function_bind_data.html", null ]
    ] ],
    [ "kuzu::common::HashIndexConstants", "structkuzu_1_1common_1_1_hash_index_constants.html", null ],
    [ "kuzu::common::HexFormatConstants", "structkuzu_1_1common_1_1_hex_format_constants.html", null ],
    [ "kuzu::common::InMemOverflowBuffer", "classkuzu_1_1common_1_1_in_mem_overflow_buffer.html", null ],
    [ "kuzu::common::Int128_t", "classkuzu_1_1common_1_1_int128__t.html", null ],
    [ "kuzu::common::int128_t", "structkuzu_1_1common_1_1int128__t.html", null ],
    [ "kuzu::common::internalID_t", "structkuzu_1_1common_1_1internal_i_d__t.html", null ],
    [ "kuzu::common::InternalKeyword", "structkuzu_1_1common_1_1_internal_keyword.html", null ],
    [ "kuzu::common::Interval", "classkuzu_1_1common_1_1_interval.html", null ],
    [ "kuzu::common::interval_t", "structkuzu_1_1common_1_1interval__t.html", null ],
    [ "kuzu::common::ku_list_t", "structkuzu_1_1common_1_1ku__list__t.html", null ],
    [ "kuzu::common::ku_string_t", "structkuzu_1_1common_1_1ku__string__t.html", null ],
    [ "kuzu::common::list_entry_t", "structkuzu_1_1common_1_1list__entry__t.html", null ],
    [ "kuzu::common::ListVector", "classkuzu_1_1common_1_1_list_vector.html", null ],
    [ "kuzu::common::LoggerConstants", "structkuzu_1_1common_1_1_logger_constants.html", null ],
    [ "kuzu::common::LogicalType", "classkuzu_1_1common_1_1_logical_type.html", null ],
    [ "kuzu::common::LogicalTypeUtils", "classkuzu_1_1common_1_1_logical_type_utils.html", null ],
    [ "kuzu::common::map_entry_t", "structkuzu_1_1common_1_1map__entry__t.html", null ],
    [ "kuzu::common::MapType", "structkuzu_1_1common_1_1_map_type.html", null ],
    [ "kuzu::common::MapVector", "classkuzu_1_1common_1_1_map_vector.html", null ],
    [ "kuzu::storage::MemoryAllocator", "classkuzu_1_1storage_1_1_memory_allocator.html", null ],
    [ "kuzu::storage::MemoryBuffer", "classkuzu_1_1storage_1_1_memory_buffer.html", null ],
    [ "kuzu::storage::MemoryManager", "classkuzu_1_1storage_1_1_memory_manager.html", null ],
    [ "kuzu::common::NodeType", "structkuzu_1_1common_1_1_node_type.html", null ],
    [ "kuzu::common::NullMask", "classkuzu_1_1common_1_1_null_mask.html", null ],
    [ "kuzu::common::OrderByConstants", "structkuzu_1_1common_1_1_order_by_constants.html", null ],
    [ "kuzu::common::overflow_value_t", "structkuzu_1_1common_1_1overflow__value__t.html", null ],
    [ "kuzu::common::ParquetConstants", "structkuzu_1_1common_1_1_parquet_constants.html", null ],
    [ "kuzu::common::PhysicalTypeUtils", "structkuzu_1_1common_1_1_physical_type_utils.html", null ],
    [ "kuzu::common::PlannerKnobs", "structkuzu_1_1common_1_1_planner_knobs.html", null ],
    [ "kuzu::main::PreparedStatement", "classkuzu_1_1main_1_1_prepared_statement.html", null ],
    [ "kuzu::main::PreparedSummary", "structkuzu_1_1main_1_1_prepared_summary.html", null ],
    [ "kuzu::main::QueryResult", "classkuzu_1_1main_1_1_query_result.html", null ],
    [ "kuzu::main::QuerySummary", "classkuzu_1_1main_1_1_query_summary.html", null ],
    [ "kuzu::common::RdfReaderConfig", "structkuzu_1_1common_1_1_rdf_reader_config.html", null ],
    [ "kuzu::common::ReaderConfig", "structkuzu_1_1common_1_1_reader_config.html", null ],
    [ "kuzu::common::RelType", "structkuzu_1_1common_1_1_rel_type.html", null ],
    [ "kuzu::common::SelectionVector", "classkuzu_1_1common_1_1_selection_vector.html", null ],
    [ "kuzu::common::StorageConstants", "structkuzu_1_1common_1_1_storage_constants.html", null ],
    [ "kuzu::common::StringVector", "classkuzu_1_1common_1_1_string_vector.html", null ],
    [ "kuzu::common::struct_entry_t", "structkuzu_1_1common_1_1struct__entry__t.html", null ],
    [ "kuzu::common::StructField", "classkuzu_1_1common_1_1_struct_field.html", null ],
    [ "kuzu::common::StructType", "structkuzu_1_1common_1_1_struct_type.html", null ],
    [ "kuzu::common::StructVector", "classkuzu_1_1common_1_1_struct_vector.html", null ],
    [ "kuzu::main::SystemConfig", "structkuzu_1_1main_1_1_system_config.html", null ],
    [ "kuzu::function::TernaryFunctionExecutor", "structkuzu_1_1function_1_1_ternary_function_executor.html", null ],
    [ "kuzu::function::TernaryFunctionWrapper", "structkuzu_1_1function_1_1_ternary_function_wrapper.html", null ],
    [ "kuzu::function::TernaryListFunctionWrapper", "structkuzu_1_1function_1_1_ternary_list_function_wrapper.html", null ],
    [ "kuzu::function::TernaryStringFunctionWrapper", "structkuzu_1_1function_1_1_ternary_string_function_wrapper.html", null ],
    [ "kuzu::function::TernaryUDFExecutor", "structkuzu_1_1function_1_1_ternary_u_d_f_executor.html", null ],
    [ "kuzu::function::TernaryUDFFunctionWrapper", "structkuzu_1_1function_1_1_ternary_u_d_f_function_wrapper.html", null ],
    [ "kuzu::common::Time", "classkuzu_1_1common_1_1_time.html", null ],
    [ "kuzu::common::Timer", "classkuzu_1_1common_1_1_timer.html", null ],
    [ "kuzu::common::Timestamp", "classkuzu_1_1common_1_1_timestamp.html", null ],
    [ "kuzu::common::timestamp_t", "structkuzu_1_1common_1_1timestamp__t.html", null ],
    [ "kuzu::function::UDF", "structkuzu_1_1function_1_1_u_d_f.html", null ],
    [ "kuzu::function::UnaryCastFunctionWrapper", "structkuzu_1_1function_1_1_unary_cast_function_wrapper.html", null ],
    [ "kuzu::function::UnaryCastStringFunctionWrapper", "structkuzu_1_1function_1_1_unary_cast_string_function_wrapper.html", null ],
    [ "kuzu::function::UnaryFunctionExecutor", "structkuzu_1_1function_1_1_unary_function_executor.html", null ],
    [ "kuzu::function::UnaryFunctionWrapper", "structkuzu_1_1function_1_1_unary_function_wrapper.html", null ],
    [ "kuzu::function::UnaryListFunctionWrapper", "structkuzu_1_1function_1_1_unary_list_function_wrapper.html", null ],
    [ "kuzu::function::UnaryStringFunctionWrapper", "structkuzu_1_1function_1_1_unary_string_function_wrapper.html", null ],
    [ "kuzu::function::UnaryTryCastFunctionWrapper", "structkuzu_1_1function_1_1_unary_try_cast_function_wrapper.html", null ],
    [ "kuzu::function::UnaryUDFExecutor", "structkuzu_1_1function_1_1_unary_u_d_f_executor.html", null ],
    [ "kuzu::function::UnaryUDFFunctionWrapper", "structkuzu_1_1function_1_1_unary_u_d_f_function_wrapper.html", null ],
    [ "kuzu::common::union_entry_t", "structkuzu_1_1common_1_1union__entry__t.html", null ],
    [ "kuzu::common::UnionType", "structkuzu_1_1common_1_1_union_type.html", null ],
    [ "kuzu::common::UnionVector", "classkuzu_1_1common_1_1_union_vector.html", null ],
    [ "kuzu::common::Value::Val", "unionkuzu_1_1common_1_1_value_1_1_val.html", null ],
    [ "kuzu::common::Value", "classkuzu_1_1common_1_1_value.html", null ],
    [ "kuzu::common::ValueVector", "classkuzu_1_1common_1_1_value_vector.html", null ],
    [ "kuzu::common::VarListType", "structkuzu_1_1common_1_1_var_list_type.html", null ]
];