var hierarchy =
[
    [ "kuzu::main::ActiveQuery", "structkuzu_1_1main_1_1_active_query.html", null ],
    [ "kuzu::common::ArrayType", "structkuzu_1_1common_1_1_array_type.html", null ],
    [ "ArrowArray", "struct_arrow_array.html", [
      [ "ArrowArrayWrapper", "struct_arrow_array_wrapper.html", null ]
    ] ],
    [ "ArrowSchema", "struct_arrow_schema.html", [
      [ "ArrowSchemaWrapper", "struct_arrow_schema_wrapper.html", null ]
    ] ],
    [ "kuzu::common::AuxiliaryBuffer", "classkuzu_1_1common_1_1_auxiliary_buffer.html", [
      [ "kuzu::common::ArrowColumnAuxiliaryBuffer", "classkuzu_1_1common_1_1_arrow_column_auxiliary_buffer.html", null ],
      [ "kuzu::common::ListAuxiliaryBuffer", "classkuzu_1_1common_1_1_list_auxiliary_buffer.html", null ],
      [ "kuzu::common::StringAuxiliaryBuffer", "classkuzu_1_1common_1_1_string_auxiliary_buffer.html", null ],
      [ "kuzu::common::StructAuxiliaryBuffer", "classkuzu_1_1common_1_1_struct_auxiliary_buffer.html", null ]
    ] ],
    [ "kuzu::common::AuxiliaryBufferFactory", "classkuzu_1_1common_1_1_auxiliary_buffer_factory.html", null ],
    [ "kuzu::function::BinaryComparisonFunctionWrapper", "structkuzu_1_1function_1_1_binary_comparison_function_wrapper.html", null ],
    [ "kuzu::function::BinaryFunctionExecutor::BinaryComparisonSelectWrapper", "structkuzu_1_1function_1_1_binary_function_executor_1_1_binary_comparison_select_wrapper.html", null ],
    [ "kuzu::function::BinaryFunctionExecutor", "structkuzu_1_1function_1_1_binary_function_executor.html", null ],
    [ "kuzu::function::BinaryFunctionWrapper", "structkuzu_1_1function_1_1_binary_function_wrapper.html", null ],
    [ "kuzu::function::BinaryListExtractFunctionWrapper", "structkuzu_1_1function_1_1_binary_list_extract_function_wrapper.html", null ],
    [ "kuzu::function::BinaryListStructFunctionWrapper", "structkuzu_1_1function_1_1_binary_list_struct_function_wrapper.html", null ],
    [ "kuzu::function::BinaryMapCreationFunctionWrapper", "structkuzu_1_1function_1_1_binary_map_creation_function_wrapper.html", null ],
    [ "kuzu::function::BinaryFunctionExecutor::BinarySelectWrapper", "structkuzu_1_1function_1_1_binary_function_executor_1_1_binary_select_wrapper.html", null ],
    [ "kuzu::function::BinaryStringFunctionWrapper", "structkuzu_1_1function_1_1_binary_string_function_wrapper.html", null ],
    [ "kuzu::function::BinaryUDFExecutor", "structkuzu_1_1function_1_1_binary_u_d_f_executor.html", null ],
    [ "kuzu::function::BinaryUDFFunctionWrapper", "structkuzu_1_1function_1_1_binary_u_d_f_function_wrapper.html", null ],
    [ "kuzu::common::Blob", "structkuzu_1_1common_1_1_blob.html", null ],
    [ "kuzu::common::blob_t", "structkuzu_1_1common_1_1blob__t.html", null ],
    [ "kuzu::common::BlobVector", "structkuzu_1_1common_1_1_blob_vector.html", null ],
    [ "kuzu::common::BufferBlock", "structkuzu_1_1common_1_1_buffer_block.html", null ],
    [ "kuzu::common::BufferPoolConstants", "structkuzu_1_1common_1_1_buffer_pool_constants.html", null ],
    [ "kuzu::common::CaseInsensitiveStringEquality", "structkuzu_1_1common_1_1_case_insensitive_string_equality.html", null ],
    [ "kuzu::common::CaseInsensitiveStringHashFunction", "structkuzu_1_1common_1_1_case_insensitive_string_hash_function.html", null ],
    [ "kuzu::main::ClientConfig", "structkuzu_1_1main_1_1_client_config.html", null ],
    [ "kuzu::main::ClientConfigDefault", "structkuzu_1_1main_1_1_client_config_default.html", null ],
    [ "kuzu::main::ClientContext", "classkuzu_1_1main_1_1_client_context.html", null ],
    [ "kuzu::main::Connection", "classkuzu_1_1main_1_1_connection.html", null ],
    [ "kuzu::function::ConstFunctionExecutor", "structkuzu_1_1function_1_1_const_function_executor.html", null ],
    [ "kuzu::common::CopyConstants", "structkuzu_1_1common_1_1_copy_constants.html", null ],
    [ "kuzu::processor::CopyFromFileError", "structkuzu_1_1processor_1_1_copy_from_file_error.html", null ],
    [ "kuzu::common::CSVOption", "structkuzu_1_1common_1_1_c_s_v_option.html", null ],
    [ "kuzu::common::CSVReaderConfig", "structkuzu_1_1common_1_1_c_s_v_reader_config.html", null ],
    [ "kuzu::main::Database", "classkuzu_1_1main_1_1_database.html", null ],
    [ "kuzu::common::DataChunk", "classkuzu_1_1common_1_1_data_chunk.html", null ],
    [ "kuzu::common::DataChunkState", "classkuzu_1_1common_1_1_data_chunk_state.html", null ],
    [ "kuzu::common::Date", "classkuzu_1_1common_1_1_date.html", null ],
    [ "kuzu::common::date_t", "structkuzu_1_1common_1_1date__t.html", null ],
    [ "kuzu::main::DBConfig", "structkuzu_1_1main_1_1_d_b_config.html", null ],
    [ "kuzu::common::DecimalType", "structkuzu_1_1common_1_1_decimal_type.html", null ],
    [ "kuzu::common::dtime_t", "structkuzu_1_1common_1_1dtime__t.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "kuzu::binder::Expression", "classkuzu_1_1binder_1_1_expression.html", null ]
    ] ],
    [ "std::exception", null, [
      [ "kuzu::common::Exception", "classkuzu_1_1common_1_1_exception.html", [
        [ "kuzu::common::BinderException", "classkuzu_1_1common_1_1_binder_exception.html", null ],
        [ "kuzu::common::CatalogException", "classkuzu_1_1common_1_1_catalog_exception.html", null ],
        [ "kuzu::common::InternalException", "classkuzu_1_1common_1_1_internal_exception.html", null ]
      ] ]
    ] ],
    [ "kuzu::common::ExportCSVConstants", "structkuzu_1_1common_1_1_export_c_s_v_constants.html", null ],
    [ "kuzu::binder::ExpressionEquality", "structkuzu_1_1binder_1_1_expression_equality.html", null ],
    [ "kuzu::binder::ExpressionHasher", "structkuzu_1_1binder_1_1_expression_hasher.html", null ],
    [ "kuzu::common::ExpressionTypeUtil", "structkuzu_1_1common_1_1_expression_type_util.html", null ],
    [ "kuzu::function::ExtraTableFuncBindInput", "structkuzu_1_1function_1_1_extra_table_func_bind_input.html", [
      [ "kuzu::function::ExtraScanTableFuncBindInput", "structkuzu_1_1function_1_1_extra_scan_table_func_bind_input.html", null ]
    ] ],
    [ "kuzu::common::ExtraTypeInfo", "classkuzu_1_1common_1_1_extra_type_info.html", [
      [ "kuzu::common::DecimalTypeInfo", "classkuzu_1_1common_1_1_decimal_type_info.html", null ],
      [ "kuzu::common::ListTypeInfo", "classkuzu_1_1common_1_1_list_type_info.html", [
        [ "kuzu::common::ArrayTypeInfo", "classkuzu_1_1common_1_1_array_type_info.html", null ]
      ] ],
      [ "kuzu::common::StructTypeInfo", "classkuzu_1_1common_1_1_struct_type_info.html", null ],
      [ "kuzu::common::UDTTypeInfo", "classkuzu_1_1common_1_1_u_d_t_type_info.html", null ]
    ] ],
    [ "kuzu::common::FileTypeInfo", "structkuzu_1_1common_1_1_file_type_info.html", null ],
    [ "kuzu::common::FileTypeUtils", "structkuzu_1_1common_1_1_file_type_utils.html", null ],
    [ "kuzu::processor::FlatTuple", "classkuzu_1_1processor_1_1_flat_tuple.html", null ],
    [ "Funcs...", null, [
      [ "kuzu::common::overload< Funcs >", "structkuzu_1_1common_1_1overload.html", null ]
    ] ],
    [ "kuzu::function::Function", "structkuzu_1_1function_1_1_function.html", [
      [ "kuzu::function::ScalarOrAggregateFunction", "structkuzu_1_1function_1_1_scalar_or_aggregate_function.html", [
        [ "kuzu::function::ScalarFunction", "structkuzu_1_1function_1_1_scalar_function.html", null ]
      ] ],
      [ "kuzu::function::TableFunction", "structkuzu_1_1function_1_1_table_function.html", null ]
    ] ],
    [ "kuzu::function::FunctionBindData", "structkuzu_1_1function_1_1_function_bind_data.html", [
      [ "kuzu::function::CastFunctionBindData", "structkuzu_1_1function_1_1_cast_function_bind_data.html", null ]
    ] ],
    [ "std::hash< kuzu::common::int128_t >", "structstd_1_1hash_3_01kuzu_1_1common_1_1int128__t_01_4.html", null ],
    [ "kuzu::common::HashIndexConstants", "structkuzu_1_1common_1_1_hash_index_constants.html", null ],
    [ "kuzu::common::HexFormatConstants", "structkuzu_1_1common_1_1_hex_format_constants.html", null ],
    [ "kuzu::common::ImportDBConstants", "structkuzu_1_1common_1_1_import_d_b_constants.html", null ],
    [ "kuzu::common::InMemOverflowBuffer", "classkuzu_1_1common_1_1_in_mem_overflow_buffer.html", null ],
    [ "kuzu::common::Int128_t", "classkuzu_1_1common_1_1_int128__t.html", null ],
    [ "kuzu::common::int128_t", "structkuzu_1_1common_1_1int128__t.html", null ],
    [ "kuzu::common::internalID_t", "structkuzu_1_1common_1_1internal_i_d__t.html", null ],
    [ "kuzu::common::InternalKeyword", "structkuzu_1_1common_1_1_internal_keyword.html", null ],
    [ "kuzu::common::Interval", "classkuzu_1_1common_1_1_interval.html", null ],
    [ "kuzu::common::interval_t", "structkuzu_1_1common_1_1interval__t.html", null ],
    [ "kuzu::common::ku_list_t", "structkuzu_1_1common_1_1ku__list__t.html", null ],
    [ "kuzu::common::ku_string_t", "structkuzu_1_1common_1_1ku__string__t.html", null ],
    [ "kuzu::common::ku_uuid_t", "structkuzu_1_1common_1_1ku__uuid__t.html", null ],
    [ "kuzu::processor::LineContext", "structkuzu_1_1processor_1_1_line_context.html", null ],
    [ "kuzu::common::list_entry_t", "structkuzu_1_1common_1_1list__entry__t.html", null ],
    [ "kuzu::common::ListType", "structkuzu_1_1common_1_1_list_type.html", null ],
    [ "kuzu::common::ListVector", "classkuzu_1_1common_1_1_list_vector.html", null ],
    [ "kuzu::common::LogicalType", "classkuzu_1_1common_1_1_logical_type.html", null ],
    [ "kuzu::common::LogicalTypeUtils", "structkuzu_1_1common_1_1_logical_type_utils.html", null ],
    [ "kuzu::common::map_entry_t", "structkuzu_1_1common_1_1map__entry__t.html", null ],
    [ "kuzu::common::MapType", "structkuzu_1_1common_1_1_map_type.html", null ],
    [ "kuzu::common::MapVector", "classkuzu_1_1common_1_1_map_vector.html", null ],
    [ "kuzu::common::NestedVal", "classkuzu_1_1common_1_1_nested_val.html", null ],
    [ "kuzu::common::NodeVal", "classkuzu_1_1common_1_1_node_val.html", null ],
    [ "kuzu::common::NullMask", "classkuzu_1_1common_1_1_null_mask.html", null ],
    [ "kuzu::main::Option", "structkuzu_1_1main_1_1_option.html", [
      [ "kuzu::main::ConfigurationOption", "structkuzu_1_1main_1_1_configuration_option.html", null ],
      [ "kuzu::main::ExtensionOption", "structkuzu_1_1main_1_1_extension_option.html", null ]
    ] ],
    [ "kuzu::common::OrderByConstants", "structkuzu_1_1common_1_1_order_by_constants.html", null ],
    [ "kuzu::common::overflow_value_t", "structkuzu_1_1common_1_1overflow__value__t.html", null ],
    [ "kuzu::common::ParquetConstants", "structkuzu_1_1common_1_1_parquet_constants.html", null ],
    [ "kuzu::common::PathSemanticUtils", "structkuzu_1_1common_1_1_path_semantic_utils.html", null ],
    [ "kuzu::common::PhysicalTypeUtils", "structkuzu_1_1common_1_1_physical_type_utils.html", null ],
    [ "kuzu::common::PlannerKnobs", "structkuzu_1_1common_1_1_planner_knobs.html", null ],
    [ "kuzu::function::PointerFunctionExecutor", "structkuzu_1_1function_1_1_pointer_function_executor.html", null ],
    [ "kuzu::processor::PopulatedCopyFromError", "structkuzu_1_1processor_1_1_populated_copy_from_error.html", null ],
    [ "kuzu::main::PreparedStatement", "classkuzu_1_1main_1_1_prepared_statement.html", null ],
    [ "kuzu::main::PreparedSummary", "structkuzu_1_1main_1_1_prepared_summary.html", null ],
    [ "kuzu::main::QueryResult", "classkuzu_1_1main_1_1_query_result.html", null ],
    [ "kuzu::main::QuerySummary", "classkuzu_1_1main_1_1_query_summary.html", null ],
    [ "kuzu::common::ReaderConfig", "structkuzu_1_1common_1_1_reader_config.html", null ],
    [ "kuzu::common::RecursiveRelVal", "classkuzu_1_1common_1_1_recursive_rel_val.html", null ],
    [ "kuzu::common::RelVal", "classkuzu_1_1common_1_1_rel_val.html", null ],
    [ "kuzu::function::ScalarBindFuncInput", "structkuzu_1_1function_1_1_scalar_bind_func_input.html", null ],
    [ "kuzu::function::ScanReplacement", "structkuzu_1_1function_1_1_scan_replacement.html", null ],
    [ "kuzu::function::ScanReplacementData", "structkuzu_1_1function_1_1_scan_replacement_data.html", null ],
    [ "kuzu::common::SelectionVector", "classkuzu_1_1common_1_1_selection_vector.html", null ],
    [ "kuzu::parser::Statement", "classkuzu_1_1parser_1_1_statement.html", null ],
    [ "kuzu::common::StorageConstants", "structkuzu_1_1common_1_1_storage_constants.html", null ],
    [ "kuzu::main::StorageDriver", "classkuzu_1_1main_1_1_storage_driver.html", null ],
    [ "kuzu::storage::StorageVersionInfo", "structkuzu_1_1storage_1_1_storage_version_info.html", null ],
    [ "kuzu::common::StringVector", "classkuzu_1_1common_1_1_string_vector.html", null ],
    [ "kuzu::common::struct_entry_t", "structkuzu_1_1common_1_1struct__entry__t.html", null ],
    [ "kuzu::common::StructField", "classkuzu_1_1common_1_1_struct_field.html", null ],
    [ "kuzu::common::StructType", "structkuzu_1_1common_1_1_struct_type.html", null ],
    [ "kuzu::common::StructVector", "classkuzu_1_1common_1_1_struct_vector.html", null ],
    [ "kuzu::main::SystemConfig", "structkuzu_1_1main_1_1_system_config.html", null ],
    [ "kuzu::function::TableFuncBindInput", "structkuzu_1_1function_1_1_table_func_bind_input.html", null ],
    [ "kuzu::function::TableFuncInput", "structkuzu_1_1function_1_1_table_func_input.html", null ],
    [ "kuzu::function::TableFuncLocalState", "structkuzu_1_1function_1_1_table_func_local_state.html", null ],
    [ "kuzu::function::TableFuncOutput", "structkuzu_1_1function_1_1_table_func_output.html", null ],
    [ "kuzu::function::TableFuncSharedState", "structkuzu_1_1function_1_1_table_func_shared_state.html", null ],
    [ "kuzu::function::TableFunctionInitInput", "structkuzu_1_1function_1_1_table_function_init_input.html", null ],
    [ "kuzu::function::TernaryFunctionExecutor", "structkuzu_1_1function_1_1_ternary_function_executor.html", null ],
    [ "kuzu::function::TernaryFunctionWrapper", "structkuzu_1_1function_1_1_ternary_function_wrapper.html", null ],
    [ "kuzu::function::TernaryListFunctionWrapper", "structkuzu_1_1function_1_1_ternary_list_function_wrapper.html", null ],
    [ "kuzu::function::TernaryRegexFunctionWrapper", "structkuzu_1_1function_1_1_ternary_regex_function_wrapper.html", null ],
    [ "kuzu::function::TernaryStringFunctionWrapper", "structkuzu_1_1function_1_1_ternary_string_function_wrapper.html", null ],
    [ "kuzu::function::TernaryUDFExecutor", "structkuzu_1_1function_1_1_ternary_u_d_f_executor.html", null ],
    [ "kuzu::function::TernaryUDFFunctionWrapper", "structkuzu_1_1function_1_1_ternary_u_d_f_function_wrapper.html", null ],
    [ "kuzu::common::Time", "classkuzu_1_1common_1_1_time.html", null ],
    [ "kuzu::common::Timer", "classkuzu_1_1common_1_1_timer.html", null ],
    [ "kuzu::common::Timestamp", "classkuzu_1_1common_1_1_timestamp.html", null ],
    [ "kuzu::common::timestamp_t", "structkuzu_1_1common_1_1timestamp__t.html", [
      [ "kuzu::common::timestamp_ms_t", "structkuzu_1_1common_1_1timestamp__ms__t.html", null ],
      [ "kuzu::common::timestamp_ns_t", "structkuzu_1_1common_1_1timestamp__ns__t.html", null ],
      [ "kuzu::common::timestamp_sec_t", "structkuzu_1_1common_1_1timestamp__sec__t.html", null ],
      [ "kuzu::common::timestamp_tz_t", "structkuzu_1_1common_1_1timestamp__tz__t.html", null ]
    ] ],
    [ "kuzu::transaction::Transaction", "classkuzu_1_1transaction_1_1_transaction.html", null ],
    [ "kuzu::transaction::TransactionContext", "classkuzu_1_1transaction_1_1_transaction_context.html", null ],
    [ "kuzu::common::TypeUtils", "classkuzu_1_1common_1_1_type_utils.html", null ],
    [ "kuzu::function::UDF", "structkuzu_1_1function_1_1_u_d_f.html", null ],
    [ "kuzu::function::UnaryCastFunctionWrapper", "structkuzu_1_1function_1_1_unary_cast_function_wrapper.html", null ],
    [ "kuzu::function::UnaryCastStringFunctionWrapper", "structkuzu_1_1function_1_1_unary_cast_string_function_wrapper.html", null ],
    [ "kuzu::function::UnaryFunctionExecutor", "structkuzu_1_1function_1_1_unary_function_executor.html", null ],
    [ "kuzu::function::UnaryFunctionWrapper", "structkuzu_1_1function_1_1_unary_function_wrapper.html", null ],
    [ "kuzu::function::UnaryNestedTypeFunctionWrapper", "structkuzu_1_1function_1_1_unary_nested_type_function_wrapper.html", null ],
    [ "kuzu::function::UnarySequenceFunctionWrapper", "structkuzu_1_1function_1_1_unary_sequence_function_wrapper.html", null ],
    [ "kuzu::function::UnaryStringFunctionWrapper", "structkuzu_1_1function_1_1_unary_string_function_wrapper.html", null ],
    [ "kuzu::function::UnaryStructFunctionWrapper", "structkuzu_1_1function_1_1_unary_struct_function_wrapper.html", null ],
    [ "kuzu::function::UnaryUDFExecutor", "structkuzu_1_1function_1_1_unary_u_d_f_executor.html", null ],
    [ "kuzu::function::UnaryUDFFunctionWrapper", "structkuzu_1_1function_1_1_unary_u_d_f_function_wrapper.html", null ],
    [ "kuzu::common::union_entry_t", "structkuzu_1_1common_1_1union__entry__t.html", null ],
    [ "kuzu::common::UnionType", "structkuzu_1_1common_1_1_union_type.html", null ],
    [ "kuzu::common::UnionVector", "classkuzu_1_1common_1_1_union_vector.html", null ],
    [ "kuzu::common::UUID", "structkuzu_1_1common_1_1_u_u_i_d.html", null ],
    [ "kuzu::common::Value::Val", "unionkuzu_1_1common_1_1_value_1_1_val.html", null ],
    [ "kuzu::common::Value", "classkuzu_1_1common_1_1_value.html", null ],
    [ "kuzu::common::ValueVector", "classkuzu_1_1common_1_1_value_vector.html", null ],
    [ "kuzu::main::Version", "structkuzu_1_1main_1_1_version.html", null ],
    [ "kuzu::common::WarningConstants", "structkuzu_1_1common_1_1_warning_constants.html", null ],
    [ "kuzu::processor::WarningContext", "classkuzu_1_1processor_1_1_warning_context.html", null ],
    [ "kuzu::processor::WarningInfo", "structkuzu_1_1processor_1_1_warning_info.html", null ],
    [ "kuzu::processor::WarningSourceData", "structkuzu_1_1processor_1_1_warning_source_data.html", null ]
];